server:
  port: 443
  context-path: /
  ssl:
    enabled: true
    key-store: src/main/resources/bilibili.p12
    key-store-type: PKCS12
    key-store-password: changeit

springboot:
  fileupload:
    base-path: F:/workspace/danmuk-repo/download/
    directory: upload